### ISSUE TITLE
Use role params sparingly -- use role defaults and external variable files. 

### ISSUE THREAD

**Issue by tima** [stephenpc/ansible-satellite#2]
Re:

```
      sat_products:
        - name: "Red Hat Enterprise Linux Server"
          repos:
            - name: "Red Hat Enterprise Linux 7 Server (RPMs)"
              options: "--releasever 7Server --basearch x86_64"
              arch: "x86_64"
              release: "7Server"
            - name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
              options: "--basearch x86_64"
              arch: "x86_64"
              release: ""
            - name: "Red Hat Satellite Tools 6.1 (for RHEL 7 Server) (RPMs)"
              options: "--basearch x86_64"
              arch: "x86_64"
              release: "7Server"
            - name: "Red Hat Enterprise Linux 7 Server (RPMs)"
              options: "--releasever 7.1 --basearch x86_64"
              arch: "x86_64"
              release: "7.1"
```

While roles can take in parameters we recommend using them sparingly. Roles parameters should be reserved for common and quick modification of a roles behavior. For example like the apache role we demonstrated where you want to give the user quick assess to defining an alternate port. 

Also, it's a general best practice to avoid hard coding variables (whether they be parameters passed to a role or a play vars) especially with the number and complexity of what you have.

Not being familiar with Satellite and what you are doing there are two different ways you could better implement these -- perhaps both apply. Make use of role defaults for "automagically" defining variables and setting them with "reasonable" values. Since defaults are easily overridden the end user can change any values that they need to. If they don't care you taken care of it for them. If there are some variables where you don't want to make it harder (but not impossible) for them to override the value of a variable use the roles vars/ folder instead where they have a high precedence. If you absolutely do not want them to be able to change a given value/parameter then hard code it where ever necessary.

Lastly pertaining to blocks like these, if your role is implementing an extensive number of configuration parameters/data like above I'd recommend that you pass a single parameter -- a path to a variable file -- and have Ansible read that in immediately in your tasks instead of inlining all of that in your playbook.
